name: ImagePreviewer
version: '1.0'
main: io.wdsj.imagepreviewer.ImagePreviewer
api-version: '1.13'
authors:
  - 0D00_0721
  - HaHaWTH
folia-supported: true
depend:
  - packetevents
permissions:
  imagepreviewer.*:
    default: false
    description: Allows access to all commands and features of the plugin.
    children:
      imagepreviewer.use: true
      imagepreviewer.command.reload: true
      imagepreviewer.command.help: true
  imagepreviewer.command.reload:
    default: op
    description: Allows the reloading of the plugin's configuration.
  imagepreviewer.command.help:
    default: true
    description: Allows the display of the plugin's help menu.
  imagepreviewer.use:
    default: true
    description: Allows the use of the plugin.
commands:
  imagepreviewer:
    description: The main command for the plugin.
    usage: /imagepreviewer
    aliases: [imagepreview, preview]
